[workspace]
preview = ["pixi-build"]
channels = ["conda-forge", "nodefaults"]
platforms = ["osx-64"]

[package]
authors = ["Nodar Gogoberidze <gnodar01@gmail.com>"]
name = "nbdotrun"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package.host-dependencies]
hatchling = "*"
nodejs = ">=22.13.0,<22.14"
hatch-nodejs-version = ">=0.3.2,<0.4"
hatch-jupyter-builder = ">=0.9.1,<0.10"

[tasks]
list_exts = { cmd = ["eza", "--long", "--all", "--git", "--header", "--icons=auto", "--classify=auto", "$CONDA_PREFIX/share/jupyter/labextensions", "&&", "jupyter", "labextension", "list"] }
dev_exts = { cmd = ["jupyter", "labextension", "develop", "--overwrite", "./"] }
jlpm = { cmd = ["jlpm", "run"] }
jlpm_add = { cmd = ["jlpm", "add"] }
jlpm_init = { cmd = ["jlpm", "install", "&&", "jlpm", "build"] }
launch_jl = { cmd = ["jupyter", "lab"] }
build = { cmd = ["python", "-m", "build"] }
publish = { cmd = ["python", "-m", "twine", "upload", "dist/*"] }
grayskull = { cmd = ["grayskull", "pypi", "--strict-conda-forge", "nbdotrun"] }

[dependencies]
python = "3.10.*"
jupyterlab = "4.*"
nodejs = "18.*"
grayskull = ">=2.9.1,<3"

[pypi-dependencies]
nbdotrun = { path = ".", editable = true }
jldracula = ">=0.2.0, <0.3"
build = ">=1.2.2.post1, <2"
twine = ">=6.1.0, <7"
